---
functional:
  - Пользователь может зарегистрироваться
  - Пользователь может авторизоваться через логин и пароль
  - Пользователь может авторизоваться через аккаунт GitHub или Discord
  - Пользователь может создать игру
  - Пользователь может создать турнир
  - Пользователь может играть с другими пользователями
  - Пользователь может выбирать на каком языке написано задание (русский или английский)
  - Пользователь может выбрать уровень игры (от легкого к сложному), иначе игра сама определяет уровень
  - Пользователь может выбрать тип игры с другими пользователями или ботом
  - Пользователь может сыграть тестовую игру без регистрации
  - Пользователь может настроить продолжительность игры
  - Пользователь может выбрать тип задания
  - Зарегистрированные пользователи могут общаться друг с другом в чате
  - Пользователи в режиме игры могут видеть друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - Пользователи могут получать очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Пользователь может видеть рейтинг со списком других игроков, а также может отфильтровать его
  - Пользователь может просматривать ход игры других пользователей онлайн или через раздел истории
  - Пользователь может просматривать историю игр и турниров
  - Пользователь может посмотреть завершенную игру или турнир в записи
  - Редактор кода в завершенной игре должен выглядеть как проигрыватель
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Игра должна содержать редактор кода и поддерживать языки программирования
  - Пользователь может отправлять и получать инвайты
  - Пользователь может видеть активные вызовы и принимать их
  - Пользователь может видеть таблицу лидеров
  - Пользователь может перейти по ссылкам в навигации на ресурсы проекта
  - Пользователь может видеть количество онлайн-пользователей
  - Пользователь может установить аватар своего профиля  
  - Пользователь может установить никнейм для своего профиля
  - Пользователь может выбирать разные языки программирования для игры
  - Пользователь может выбрать мелодию для игры и установить ее громкость
  - Пользователь может просматривать список задач
  - Пользователь может создать новую задачу
